version: 2
jobs:
  build:
    
    working_directory: ~/at.jku.se.prse.example.calculator

    docker:
      - image: circleci/openjdk:16-jdk-browsers

    steps:

      - checkout
      
      - run: mvn clean verify    
      
      - store_test_results:
          path: /home/circleci/at.jku.se.prse.example.calculator/at.jku.se.prse.example.calculator/target/surefire-reports
          
      - store_artifacts:
          path: /home/circleci/at.jku.se.prse.example.calculator/at.jku.se.prse.example.calculator/target/ 
      
