version: 2
jobs:
  build:
    
    working_directory: ~/at.jku.se.prse.example.calculator

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      
      - run: mvn clean verify    
      
      - store_test_results:
          path: /tmp/circleci-test-results
          
      - store_artifacts:
          path: /tmp/circleci-artifacts 
      